const M=(()=>{
 const KEY="metodika-v1-data", uid=()=>Math.random().toString(36).slice(2)+Date.now().toString(36);
 let data={players:[],matches:[]},view="home",activeId=null,step=1,timer=null,deferred=null;
 try{data=JSON.parse(localStorage.getItem(KEY))||data;data.matches=(data.matches||[]).map(m=>({...m,running:false,startedAt:null}))}catch{}
 const $=s=>document.querySelector(s), save=()=>localStorage.setItem(KEY,JSON.stringify(data));
 const m=()=>data.matches.find(x=>x.id===activeId), p=id=>data.players.find(x=>x.id===id);
 const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
 const elapsed=()=>{const x=m();return x?x.elapsed+(x.running&&x.startedAt?Math.floor((Date.now()-x.startedAt)/1000):0):0};
 const fmt=n=>`${String(Math.floor(n/60)).padStart(2,"0")}:${String(n%60).padStart(2,"0")}`;
 const avatar=(x,small="")=>`<div class="avatar ${small}">${x?.photo?`<img src="${x.photo}" alt="">`:`<span>${esc(x?.name?.[0]||"?")}</span>`}</div>`;
 const top=(title,back)=>`<header class="top"><button onclick="${back}">←</button><b>${esc(title)}</b><span>METODIKA</span></header>`;
 const commit=()=>{save();render()};
 const update=fn=>{const i=data.matches.findIndex(x=>x.id===activeId);data.matches[i]=fn(data.matches[i]);commit()};
 const stamp=()=>({at:elapsed(),period:m().period});
 const add=(type,extra={})=>update(x=>({...x,events:[...x.events,{id:uid(),type,...stamp(),...extra}]}));
 const labels={goal:"Gol",rivalGoal:"Gol rival",chance:"Situación de gol",rivalChance:"Situación rival",foulFor:"Falta a favor",foulAgainst:"Falta en contra",sub:"Cambio",possession:"Posesión",loss:"Pérdida"};
 const stats=()=>{const e=m().events,ps=e.filter(x=>x.type==="possession"),passes=ps.reduce((a,x)=>a+(x.passes||0),0);return{goals:e.filter(x=>x.type==="goal").length,rivalGoals:e.filter(x=>x.type==="rivalGoal").length,chances:e.filter(x=>x.type==="chance").length,rivalChances:e.filter(x=>x.type==="rivalChance").length,foulsFor:e.filter(x=>x.type==="foulFor").length,foulsAgainst:e.filter(x=>x.type==="foulAgainst").length,possessions:ps.length,passes,avg:ps.length?(passes/ps.length).toFixed(1):"0",best:Math.max(0,...ps.map(x=>x.passes||0))}};
 const modal=(title,html)=>{document.body.insertAdjacentHTML("beforeend",`<div class="modal-bg" id="modal"><div class="modal"><header><h2>${title}</h2><button onclick="M.close()">×</button></header>${html}</div></div>`)};
 const close=()=>$("#modal")?.remove();
 const picker=(title,ids,cb,none=false)=>modal(title,`<div class="picker">${ids.map(id=>{const x=p(id);return `<button onclick="M.close();${cb}('${id}')">${avatar(x)}<b>#${esc(x.number)} ${esc(x.name)}</b></button>`}).join("")}${none?`<button class="none" onclick="M.close();${cb}('')">Sin jugadora</button>`:""}</div>`);
 const render=()=>{
  const app=$("#app"), x=m();
  if(view==="home")app.innerHTML=`<main class="shell home"><header class="brand"><div class="mark">M</div><div><h1>METODIKA</h1><p>Partido en vivo</p></div><span class="offline">● OFFLINE</span></header><section class="hero"><p class="eyebrow">VERSIÓN 1.0.0</p><h2>Todo el partido.<br><em>En una sola mano.</em></h2><p>Registrá acciones, pases y jugadoras sin perder de vista el juego.</p><button class="cta" onclick="M.go('squad')">Comenzar un partido <span>→</span></button></section><nav class="home-grid"><button onclick="M.go('squad')"><span>◉</span><b>Plantel</b><small>${data.players.length} jugadoras</small></button><button ${data.matches.length?"":"disabled"} onclick="M.openLast()"><span>▤</span><b>Partidos</b><small>${data.matches.length} guardados</small></button><button id="install" style="display:${deferred?"grid":"none"}" onclick="M.install()"><span>↓</span><b>Instalar</b><small>Acceso sin internet</small></button></nav><footer>METODIKA · V1.0.0</footer></main>`;
  if(view==="squad")app.innerHTML=`<main class="shell">${top("Plantel","M.go('home')")}<section class="page-head"><div><p class="eyebrow">TU EQUIPO</p><h2>Jugadoras</h2></div><button class="primary compact" onclick="M.playerForm()">＋ Agregar</button></section><div class="roster">${data.players.map(q=>`<article>${avatar(q)}<div><b>#${esc(q.number)} ${esc(q.name)}</b><span>${esc(q.position)}</span></div><button onclick="M.removePlayer('${q.id}')">×</button></article>`).join("")}</div>${data.players.length?"":`<div class="empty"><div>◉</div><b>Tu plantel está vacío</b><p>Agregá las jugadoras con su foto, número y posición.</p></div>`}<div class="bottom-action"><button class="cta" ${data.players.length?"":"disabled"} onclick="M.matchForm()">Nuevo partido <span>→</span></button></div></main>`;
  if(view==="setup"&&x)app.innerHTML=`<main class="shell">${top(x.rival,step===2?"M.setStep(1)":"M.go('squad')")}<section class="setup"><div class="steps"><span class="${step===1?"active":"done"}">1</span><i></i><span class="${step===2?"active":""}">2</span></div><p class="eyebrow">PASO ${step} · ${step===1?"CONVOCADAS":"TITULARES"}</p><h2>${step===1?"¿Quiénes fueron citadas?":"Elegí las 11 iniciales"}</h2><p>${step===1?x.called.length+" seleccionadas":x.starters.length+"/11 titulares"}</p></section><div class="player-select">${data.players.filter(q=>step===1||x.called.includes(q.id)).map(q=>{const sel=(step===1?x.called:x.starters).includes(q.id);return `<button class="${sel?"selected":""}" onclick="M.togglePlayer('${q.id}')">${avatar(q)}<b>#${esc(q.number)} ${esc(q.name)}</b><span>${esc(q.position)}</span><i>${sel?"✓":""}</i></button>`}).join("")}</div><div class="bottom-action">${step===1?`<button class="cta" ${x.called.length?"":"disabled"} onclick="M.setStep(2)">Continuar <span>→</span></button>`:`<button class="cta" ${x.starters.length===11?"":"disabled"} onclick="M.start()">Comenzar partido <span>▶</span></button>`}</div></main>`;
  if(view==="live"&&x){const s=stats();app.innerHTML=`<main class="live"><header class="scorebar"><div class="team"><small>${x.home?"METODIKA":esc(x.rival)}</small><strong>${s.goals}</strong></div><div class="clock"><span>${x.period}T</span><b id="clock">${fmt(elapsed())}</b><button onclick="M.pause()">${x.running?"Ⅱ PAUSA":"▶ REANUDAR"}</button></div><div class="team rival"><small>${x.home?esc(x.rival):"METODIKA"}</small><strong>${s.rivalGoals}</strong></div></header><section class="live-body"><div class="events"><h3>Acciones rápidas</h3><div class="event-grid">${btn("good","⚽","Gol","Autora + asistencia","goal")}${btn("bad","⚽","Gol rival","Un toque","rivalGoal")}${btn("good","◎","Situación de gol","Jugadora opcional","chance")}${btn("bad","◎","Situación rival","Un toque","rivalChance")}${btn("","⚑","Falta a favor","Un toque","foulFor")}${btn("","⚑","Falta en contra","Elegir jugadora","foulAgainst")}${btn("","⇄","Cambio","Sale / entra","sub")}<button onclick="M.undo()" ${x.events.length?"":"disabled"}><i>↶</i><b>Deshacer</b><span>Última acción</span></button></div></div><div class="possession ${x.possessionStart!=null?"active":""}"><div><small>${x.possessionStart!=null?"POSESIÓN ACTIVA":"CONTADOR DE PASES"}</small><strong>${x.possessionPasses}</strong><span>pases correctos</span></div>${x.possessionStart==null?`<button class="start-pos" onclick="M.possession()">▶ Iniciar posesión</button>`:`<button class="pass" onclick="M.pass()"><b>＋</b><span>PASE CORRECTO</span></button><button class="loss" onclick="M.loss()">PÉRDIDA</button>`}</div><aside class="timeline"><div class="timeline-head"><h3>Historial</h3><button onclick="M.undo()">↶</button></div><div>${[...x.events].reverse().map(e=>`<article><time>${e.period}T · ${fmt(e.at)}</time><p>${eventText(e)}</p><button onclick="M.deleteEvent('${e.id}')">×</button></article>`).join("")||`<p class="muted">Las acciones aparecerán acá.</p>`}</div></aside></section><nav class="live-nav"><button onclick="M.showPlayers()">◉ Jugadoras</button><button onclick="M.controls()">⚙ Partido</button><button onclick="M.go('summary')">▤ Estadísticas</button></nav></main>`}
  if(view==="summary"&&x){const s=stats();const vals=[["Situaciones",s.chances],["Situaciones rival",s.rivalChances],["Faltas a favor",s.foulsFor],["Faltas en contra",s.foulsAgainst],["Posesiones",s.possessions],["Pases correctos",s.passes],["Promedio / posesión",s.avg],["Mejor secuencia",s.best]];app.innerHTML=`<main class="shell">${top("Resumen",x.finished?"M.go('home')":"M.go('live')")}<section class="result"><p>${esc(x.competition||"PARTIDO")}</p><div><span>METODIKA</span><b>${s.goals} — ${s.rivalGoals}</b><span>${esc(x.rival)}</span></div><small>${esc(x.date)}</small></section><section class="stats-grid">${vals.map(v=>`<article><b>${v[1]}</b><span>${v[0]}</span></article>`).join("")}</section><section class="individual"><h2>Rendimiento individual</h2>${data.players.filter(q=>x.called.includes(q.id)).map(q=>`<article>${avatar(q,"small")}<b>#${esc(q.number)} ${esc(q.name)}</b><span>${x.events.filter(e=>e.type==="goal"&&e.playerId===q.id).length} G</span><span>${x.events.filter(e=>e.assistId===q.id).length} A</span><span>${x.events.filter(e=>e.type==="foulAgainst"&&e.playerId===q.id).length} F</span></article>`).join("")}</section></main>`}
 };
 const btn=(cl,ic,title,sub,type)=>`<button class="${cl}" onclick="M.action('${type}')"><i>${ic}</i><b>${title}</b><span>${sub}</span></button>`;
 const eventText=e=>e.type==="possession"?`${e.passes} pases · ${fmt(Math.max(0,e.at-e.startAt))}`:e.type==="sub"?`${esc(p(e.outId)?.name)} → ${esc(p(e.inId)?.name)}`:[labels[e.type],p(e.playerId)?.name,e.assistId?`Asist. ${p(e.assistId)?.name}`:""].filter(Boolean).map(esc).join(" · ");
 const action=type=>{const x=m();if(type==="goal")picker("¿Quién hizo el gol?",x.onField,"M.goalBy");if(type==="rivalGoal")add(type);if(type==="chance")picker("Situación de gol",x.onField,"M.chanceBy",true);if(type==="rivalChance"||type==="foulFor")add(type);if(type==="foulAgainst")picker("¿Quién cometió la falta?",x.onField,"M.foulBy");if(type==="sub")picker("¿Quién sale?",x.onField,"M.subOut")};
 const api={render,close,go:v=>{view=v;render()},setStep:s=>{step=s;render()},install:async()=>{if(deferred){await deferred.prompt();deferred=null;render()}},openLast:()=>{activeId=data.matches.at(-1)?.id;view="summary";render()},
  playerForm:()=>modal("Nueva jugadora",`<form id="playerForm" class="form" onsubmit="M.addPlayer(event)"><label>Foto<input name="photo" type="file" accept="image/*"></label><label>Nombre<input required name="name" placeholder="Nombre y apellido"></label><div class="two"><label>Número<input required name="number" inputmode="numeric"></label><label>Posición<select name="position"><option>Arquera</option><option>Defensora</option><option>Volante</option><option>Delantera</option></select></label></div><button class="primary">Guardar jugadora</button></form>`),
  addPlayer:ev=>{ev.preventDefault();const f=new FormData(ev.target),file=f.get("photo"),done=photo=>{data.players.push({id:uid(),name:f.get("name"),number:f.get("number"),position:f.get("position"),photo});close();commit()};if(file?.size){const r=new FileReader();r.onload=()=>{const im=new Image();im.onload=()=>{const c=document.createElement("canvas"),ctx=c.getContext("2d"),z=Math.min(im.width,im.height);c.width=c.height=240;ctx.drawImage(im,(im.width-z)/2,(im.height-z)/2,z,z,0,0,240,240);done(c.toDataURL("image/jpeg",.78))};im.src=r.result};r.readAsDataURL(file)}else done()},
  removePlayer:id=>{if(confirm("¿Eliminar esta jugadora?")){data.players=data.players.filter(x=>x.id!==id);commit()}},
  matchForm:()=>modal("Nuevo partido",`<form class="form" onsubmit="M.newMatch(event)"><label>Rival<input required name="rival" placeholder="Nombre del rival"></label><label>Competencia<input name="competition" placeholder="Torneo / amistoso"></label><label>Fecha<input required name="date" type="date" value="${new Date().toISOString().slice(0,10)}"></label><div class="seg"><label><input type="radio" name="venue" value="home" checked> Local</label><label><input type="radio" name="venue" value="away"> Visitante</label></div><button class="primary">Elegir convocadas</button></form>`),
  newMatch:ev=>{ev.preventDefault();const f=new FormData(ev.target),x={id:uid(),rival:f.get("rival"),competition:f.get("competition"),date:f.get("date"),home:f.get("venue")==="home",called:[],starters:[],onField:[],bench:[],events:[],period:1,elapsed:0,running:false,finished:false,possessionPasses:0,possessionStart:null};data.matches.push(x);activeId=x.id;step=1;view="setup";close();commit()},
  togglePlayer:id=>update(x=>{const key=step===1?"called":"starters",a=x[key],has=a.includes(id);if(step===2&&!has&&a.length>=11)return x;return{...x,[key]:has?a.filter(z=>z!==id):[...a,id]}}),
  start:()=>{view="live";update(x=>({...x,onField:[...x.starters],bench:x.called.filter(i=>!x.starters.includes(i)),running:true,startedAt:Date.now()}))},
  pause:()=>update(x=>x.running?{...x,elapsed:x.elapsed+Math.floor((Date.now()-x.startedAt)/1000),running:false,startedAt:null}:{...x,running:true,startedAt:Date.now()}),
  action,goalBy:id=>modal("¿Hubo asistencia?",`<div class="confirm-row"><button class="primary" onclick="M.assistFor('${id}')">Sí</button><button onclick="M.close();M.addGoal('${id}')">No</button></div>`),
  assistFor:id=>{close();picker("¿Quién dio la asistencia?",m().onField.filter(x=>x!==id),`M.addGoalAssist.bind(null,'${id}')`)},
  addGoal:id=>add("goal",{playerId:id}),addGoalAssist:(g,a)=>add("goal",{playerId:g,assistId:a}),chanceBy:id=>add("chance",{playerId:id||undefined}),foulBy:id=>add("foulAgainst",{playerId:id}),
  subOut:id=>picker("¿Quién entra?",m().bench,`M.subIn.bind(null,'${id}')`),subIn:(outId,inId)=>update(x=>({...x,onField:x.onField.map(i=>i===outId?inId:i),bench:x.bench.filter(i=>i!==inId),events:[...x.events,{id:uid(),type:"sub",...stamp(),outId,inId}]})),
  possession:()=>update(x=>({...x,possessionStart:elapsed(),possessionPasses:0})),pass:()=>update(x=>({...x,possessionPasses:x.possessionPasses+1})),loss:()=>update(x=>({...x,events:[...x.events,{id:uid(),type:"possession",...stamp(),startAt:x.possessionStart,passes:x.possessionPasses},{id:uid(),type:"loss",...stamp()}],possessionStart:null,possessionPasses:0})),
  undo:()=>update(x=>{const e=x.events.at(-1);if(!e)return x;if(e.type==="sub")return{...x,onField:x.onField.map(i=>i===e.inId?e.outId:i),bench:[...x.bench,e.inId],events:x.events.slice(0,-1)};return{...x,events:x.events.slice(0,-1)}}),
  deleteEvent:id=>update(x=>({...x,events:x.events.filter(e=>e.id!==id)})),
  showPlayers:()=>picker("Jugadoras en cancha",m().onField,"M.close"),
  controls:()=>modal("Control del partido",`<div class="control"><button onclick="M.close();M.pause()">${m().running?"Pausar":"Reanudar"}</button><button onclick="M.nextPeriod()">Cambiar a ${m().period===1?"2T":"1T"}</button><button class="danger" onclick="M.finish()">Finalizar partido</button></div>`),
  nextPeriod:()=>{close();update(x=>({...x,period:x.period===1?2:1,elapsed:0,running:false,startedAt:null}))},finish:()=>{close();update(x=>({...x,finished:true,running:false,elapsed:elapsed(),startedAt:null}));view="summary";render()}
 };
 window.addEventListener("beforeinstallprompt",e=>{e.preventDefault();deferred=e;render()});
 if("serviceWorker"in navigator)navigator.serviceWorker.register("./sw.js");
 timer=setInterval(()=>{const c=$("#clock");if(c&&m())c.textContent=fmt(elapsed())},1000);
 render();return api;
})();
